// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 12/2/2025, 5:35:40 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/onurerdogan/Desktop/PROJE_IPRICE/FRONT/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/onurerdogan/Desktop/PROJE_IPRICE/FRONT/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/onurerdogan/Desktop/PROJE_IPRICE/FRONT/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/onurerdogan/Desktop/PROJE_IPRICE/FRONT/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/onurerdogan/Desktop/PROJE_IPRICE/FRONT/plugins/**/*.{js,ts,mjs}","/Users/onurerdogan/Desktop/PROJE_IPRICE/FRONT/composables/**/*.{js,ts,mjs}","/Users/onurerdogan/Desktop/PROJE_IPRICE/FRONT/utils/**/*.{js,ts,mjs}","/Users/onurerdogan/Desktop/PROJE_IPRICE/FRONT/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/onurerdogan/Desktop/PROJE_IPRICE/FRONT/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/onurerdogan/Desktop/PROJE_IPRICE/FRONT/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/onurerdogan/Desktop/PROJE_IPRICE/FRONT/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = (() => {const cfg=config;cfg["darkMode"] = ["selector","[class~=\"dark\"]"];;return cfg;})();

export default resolvedConfig;