<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CompanySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $companies = [
            [
                'company_name' => 'Oktostore',
                'company_site' => 'https://www.oktostore.com/',
                'crawler_id' => 1,
                'is_marketplace' => false,
                'server_id' => 1,
                'screenshot_required' => false,
                'deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_name' => 'DR',
                'company_site' => 'https://www.dr.com.tr/',
                'crawler_id' => 1,
                'is_marketplace' => false,
                'server_id' => 1,
                'screenshot_required' => false,
                'deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_name' => 'Hepsiburada',
                'company_site' => 'https://www.hepsiburada.com',
                'crawler_id' => 1,
                'is_marketplace' => true,
                'server_id' => 1,
                'screenshot_required' => false,
                'deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_name' => 'Apple',
                'company_site' => 'https://www.apple.com/',
                'crawler_id' => 1,
                'is_marketplace' => false,
                'server_id' => 1,
                'screenshot_required' => false,
                'deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_name' => 'FashFed',
                'company_site' => 'https://www.fashfed.com/',
                'crawler_id' => 1,
                'is_marketplace' => false,
                'server_id' => 1,
                'screenshot_required' => false,
                'deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Troy',
                'url' => 'https://www.troyestore.com/',
                'marketplace' => null,
                'server' => null,
                'screenshot' => null,
                'deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Apple EDU',
                'url' => 'https://www.apple.com/tr-edu/',
                'marketplace' => null,
                'server' => null,
                'screenshot' => null,
                'deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'İdefix',
                'url' => 'https://www.idefix.com/',
                'marketplace' => null,
                'server' => null,
                'screenshot' => null,
                'deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sneaks Up',
                'url' => 'https://www.sneaksup.com/',
                'marketplace' => null,
                'server' => null,
                'screenshot' => null,
                'deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ebrar Bilgisayar',
                'url' => 'https://www.ebrarbilgisayar.com/',
                'marketplace' => null,
                'server' => null,
                'screenshot' => null,
                'deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ucuz Sepet',
                'url' => 'https://www.ucuzsepet.com/',
                'marketplace' => null,
                'server' => null,
                'screenshot' => null,
                'deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'GamingGen',
                'url' => 'https://www.gaming.gen.tr/',
                'marketplace' => null,
                'server' => null,
                'screenshot' => null,
                'deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pasaj',
                'url' => 'https://www.turkcell.com.tr/pasaj',
                'marketplace' => null,
                'server' => null,
                'screenshot' => null,
                'deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'İncehesap',
                'url' => 'https://www.incehesap.com/',
                'marketplace' => null,
                'server' => null,
                'screenshot' => null,
                'deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Forsan',
                'url' => 'https://www.forsan.com.tr/',
                'marketplace' => null,
                'server' => null,
                'screenshot' => null,
                'deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Boyner',
                'url' => 'https://www.boyner.com.tr/',
                'marketplace' => null,
                'server' => null,
                'screenshot' => null,
                'deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pozitif',
                'url' => 'https://www.pt.com.tr/',
                'marketplace' => null,
                'server' => null,
                'screenshot' => null,
                'deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_name' => 'Pazarama',
                'company_site' => 'https://www.pazarama.com/',
                'crawler_id' => 1,
                'is_marketplace' => true,
                'server_id' => 1,
                'screenshot_required' => false,
                'deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Vakkorama',
                'url' => 'https://www.vakkorama.com.tr/',
                'marketplace' => null,
                'server' => null,
                'screenshot' => null,
                'deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Gamemar',
                'url' => 'https://www.gamemar.com/',
                'marketplace' => null,
                'server' => null,
                'screenshot' => null,
                'deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Orkatek',
                'url' => 'https://www.orkatek.com.tr/',
                'marketplace' => null,
                'server' => null,
                'screenshot' => null,
                'deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Teknosa',
                'url' => 'https://www.teknosa.com/',
                'marketplace' => null,
                'server' => null,
                'screenshot' => null,
                'deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_name' => 'Amazon',
                'company_site' => 'https://www.amazon.com.tr/',
                'crawler_id' => 1,
                'is_marketplace' => true,
                'server_id' => 1,
                'screenshot_required' => false,
                'deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mediamarkt',
                'url' => 'https://www.mediamarkt.com.tr/',
                'marketplace' => null,
                'server' => null,
                'screenshot' => null,
                'deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'MobilSaray',
                'url' => 'https://www.mobilsaray.com/',
                'marketplace' => null,
                'server' => null,
                'screenshot' => null,
                'deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ucuza Yazılım',
                'url' => 'https://www.ucuzayazilim.com/',
                'marketplace' => null,
                'server' => null,
                'screenshot' => null,
                'deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Weblegelsin',
                'url' => 'https://www.weblegelsin.com/',
                'marketplace' => null,
                'server' => null,
                'screenshot' => null,
                'deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Atak BT',
                'url' => 'https://www.atakbt.com/',
                'marketplace' => null,
                'server' => null,
                'screenshot' => null,
                'deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Genay Bilgisayar',
                'url' => 'https://www.genaybilgisayar.com/',
                'marketplace' => null,
                'server' => null,
                'screenshot' => null,
                'deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'City Bilişim',
                'url' => 'https://www.citybilisim.com/',
                'marketplace' => null,
                'server' => null,
                'screenshot' => null,
                'deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Fab Bilgisayar',
                'url' => 'https://www.fabbilgisayar.com/',
                'marketplace' => null,
                'server' => null,
                'screenshot' => null,
                'deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Depo BT',
                'url' => 'https://www.depobt.com/',
                'marketplace' => null,
                'server' => null,
                'screenshot' => null,
                'deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tebilon',
                'url' => 'https://www.tebilon.com/',
                'marketplace' => null,
                'server' => null,
                'screenshot' => null,
                'deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '7 / 24 Alsak',
                'url' => 'https://724alsak.com/',
                'marketplace' => null,
                'server' => null,
                'screenshot' => null,
                'deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'PC Sepeti',
                'url' => 'https://www.pcsepeti.com/',
                'marketplace' => null,
                'server' => null,
                'screenshot' => null,
                'deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Güvenli Ticaret',
                'url' => 'https://www.guvenliticaret.net/',
                'marketplace' => null,
                'server' => null,
                'screenshot' => null,
                'deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Aykom',
                'url' => 'https://www.aykom.com.tr/',
                'marketplace' => null,
                'server' => null,
                'screenshot' => null,
                'deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Özcan Kartuş',
                'url' => 'https://www.ozcankartus.com/',
                'marketplace' => null,
                'server' => null,
                'screenshot' => null,
                'deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Projeksiyon.com.tr',
                'url' => 'https://www.projeksiyon.com.tr/',
                'marketplace' => null,
                'server' => null,
                'screenshot' => null,
                'deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Boyut Dijital',
                'url' => 'https://www.boyutdijital.com/',
                'marketplace' => null,
                'server' => null,
                'screenshot' => null,
                'deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'House of SuperStep',
                'url' => 'https://www.houseofsuperstep.com/',
                'marketplace' => null,
                'server' => null,
                'screenshot' => null,
                'deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Vatan',
                'url' => 'https://www.vatanbilgisayar.com',
                'marketplace' => null,
                'server' => null,
                'screenshot' => null,
                'deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'SuperStep',
                'url' => 'https://www.superstep.com.tr/',
                'marketplace' => null,
                'server' => null,
                'screenshot' => null,
                'deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'A101',
                'url' => 'https://www.a101.com.tr/elektronik',
                'marketplace' => null,
                'server' => null,
                'screenshot' => null,
                'deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_name' => 'PTTAvm',
                'company_site' => 'https://www.pttavm.com/',
                'crawler_id' => 1,
                'is_marketplace' => true,
                'server_id' => 1,
                'screenshot_required' => false,
                'deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_name' => 'N11',
                'company_site' => 'https://www.n11.com/',
                'crawler_id' => 1,
                'is_marketplace' => true,
                'server_id' => 1,
                'screenshot_required' => false,
                'deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_name' => 'Trendyol',
                'company_site' => 'https://www.trendyol.com/',
                'crawler_id' => 1,
                'is_marketplace' => true,
                'server_id' => 1,
                'screenshot_required' => false,
                'deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'İtopya',
                'url' => 'https://itopya.com/',
                'marketplace' => null,
                'server' => null,
                'screenshot' => null,
                'deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'TVT',
                'url' => 'https://www.tvt.com.tr/',
                'marketplace' => null,
                'server' => null,
                'screenshot' => null,
                'deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Aynet',
                'url' => 'https://www.aynetteknoloji.com/',
                'marketplace' => null,
                'server' => null,
                'screenshot' => null,
                'deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nethouse',
                'url' => 'https://www.nethouse.com.tr/',
                'marketplace' => null,
                'server' => null,
                'screenshot' => null,
                'deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ecanta',
                'url' => 'https://ecanta.com.tr/',
                'marketplace' => null,
                'server' => null,
                'screenshot' => null,
                'deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Beymen',
                'url' => 'https://www.beymen.com/tr',
                'marketplace' => null,
                'server' => null,
                'screenshot' => null,
                'deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Net Sipariş',
                'url' => 'https://www.netsiparis.com/',
                'marketplace' => null,
                'server' => null,
                'screenshot' => null,
                'deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Elit Store',
                'url' => 'https://www.elitstore.com/',
                'marketplace' => null,
                'server' => null,
                'screenshot' => null,
                'deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kosa Bilişim',
                'url' => 'https://www.kosabilisim.com/',
                'marketplace' => null,
                'server' => null,
                'screenshot' => null,
                'deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Gürgençler',
                'url' => 'https://www.gurgencler.com.tr/',
                'marketplace' => null,
                'server' => null,
                'screenshot' => null,
                'deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Babur Tech',
                'url' => 'https://www.baburtech.com/',
                'marketplace' => null,
                'server' => null,
                'screenshot' => null,
                'deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Okur Bilişim',
                'url' => 'https://okurbilisim.com/',
                'marketplace' => null,
                'server' => null,
                'screenshot' => null,
                'deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kurumsal IT',
                'url' => 'https://www.kurumsalit.com/',
                'marketplace' => null,
                'server' => null,
                'screenshot' => null,
                'deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mavitek Bilgisayar',
                'url' => 'https://www.mavitekbilgisayar.com.tr/',
                'marketplace' => null,
                'server' => null,
                'screenshot' => null,
                'deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Herbirivar.com',
                'url' => 'https://www.herbirivar.com/',
                'marketplace' => null,
                'server' => null,
                'screenshot' => null,
                'deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'BanaYeni',
                'url' => 'https://www.banayeni.com/',
                'marketplace' => null,
                'server' => null,
                'screenshot' => null,
                'deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sinerji Gen TR',
                'url' => 'https://www.sinerji.gen.tr/',
                'marketplace' => null,
                'server' => null,
                'screenshot' => null,
                'deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Avansas',
                'url' => 'https://www.avansas.com/',
                'marketplace' => null,
                'server' => null,
                'screenshot' => null,
                'deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dual Pazar',
                'url' => 'https://www.dualpazar.com/',
                'marketplace' => null,
                'server' => null,
                'screenshot' => null,
                'deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Delta Bilgisayar',
                'url' => 'https://www.deltabilgisayar.net/',
                'marketplace' => null,
                'server' => null,
                'screenshot' => null,
                'deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Uzmanlar PC',
                'url' => 'https://www.uzmanlarpc.com/',
                'marketplace' => null,
                'server' => null,
                'screenshot' => null,
                'deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nartas',
                'url' => 'https://www.nartas.com.tr/',
                'marketplace' => null,
                'server' => null,
                'screenshot' => null,
                'deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kam Bilişim',
                'url' => 'https://www.kambilisim.com/',
                'marketplace' => null,
                'server' => null,
                'screenshot' => null,
                'deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Gamer Mekanı',
                'url' => 'https://www.gamermekani.com.tr/',
                'marketplace' => null,
                'server' => null,
                'screenshot' => null,
                'deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bitmeyenkartuş',
                'url' => 'https://www.bitmeyenkartus.com.tr/',
                'marketplace' => null,
                'server' => null,
                'screenshot' => null,
                'deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Laptop.com.tr',
                'url' => 'https://www.laptop.com.tr/',
                'marketplace' => null,
                'server' => null,
                'screenshot' => null,
                'deleted' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('companies')->insert($companies);
    }
}
