"""Add is_screenshot to Company

Revision ID: aa2bfb34b05b
Revises: d6c3d492e0cd
Create Date: 2025-03-21 13:27:36.197922

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aa2bfb34b05b'
down_revision = 'd6c3d492e0cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mpn', sa.String(), nullable=True),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stocks_mpn'), 'stocks', ['mpn'], unique=False)
    op.add_column('company', sa.Column('is_screenshot', sa.Boolean(), nullable=True))


def downgrade():
    op.drop_column('company', 'is_screenshot')
    op.drop_index(op.f('ix_stocks_mpn'), table_name='stocks')
    op.drop_table('stocks')